### ISSUE TITLE
SVG-to-PNG conversion fails if given a negative X value

### ISSUE THREAD

**Issue by settinger** [diorcety/KiBlenderCad#1]
Thank you so much for publishing this! I haven't gotten it working yet on my KiCad projects, but I'm excited to learn how to make high-quality renders.

Here is one of the issues I've come across: inkscape.py fails to generate PNGs from .kicad_pcb files if the PCB area has a negative x value.

```
2021-08-05 23:54:39,404 - MainThread - __main__ - DEBUG - Opening SVG data output
2021-08-05 23:54:39,410 - MainThread - __main__ - DEBUG - Data: {'width': 77.153922, 'height': 95.001323, 'units': 'mm', 'y': -47.420103, 'x': -38.77815, 'thickness': 1.6, 'vrml': 'E:/KiCad/newbadge\\blender\\tmp/newbadge.wrl'}
2021-08-05 23:54:39,410 - MainThread - __main__ - INFO - SVGs to PNGs
2021-08-05 23:54:39,410 - MainThread - __main__ - DEBUG - Call C:\Program Files\Python39\python.exe E:\KiCad\KiBlenderCad\inkscape.py -vvvvvv E:\KiCad\newbadge\blender\tmp\badge3-B_Adhes.svg -o E:/KiCad/newbadge\blender\textures\badge3-B_Adhes.png -s 100 -u mm -38.778150:-47.420103:77.153922:95.001323
usage: E:\KiCad\KiBlenderCad\inkscape.py [-h] [-v] [-o OUTPUT] [-s SCALE]
                                         [-u UNIT]
                                         input area
E:\KiCad\KiBlenderCad\inkscape.py: error: the following arguments are required: area
2021-08-05 23:54:39,511 - MainThread - __main__ - ERROR - Error occurs in a subprogram
Traceback (most recent call last):
  File "E:\KiCad\KiBlenderCad\generator.py", line 145, in main
    sys.exit(_main(sys.argv))
  File "E:\KiCad\KiBlenderCad\generator.py", line 131, in _main
    call_program(sub_args)
  File "E:\KiCad\KiBlenderCad\generator.py", line 61, in call_program
    raise Exception("Error occurs in a subprogram")
Exception: Error occurs in a subprogram
```

The last argument is `-38.778150:-47.420103:77.153922:95.001323`, so inkscape.py treats it as an option instead of a parameter. The solution is to add a "--" to `sub_args` before the area parameter. I will make a pull request shortly :) Merci!

**Comment by diorcety** [comment]
Thanks

**Comment by diorcety** [comment]
Btw, this is strange that you have a negative value, you should have only positive values if the board is inside the page in kicad. Maybe you have junk edge polygones outside the page.

**Comment by settinger** [comment]
Yes, I realize it's an uncommon edge-case. The PCB I wanted to render is...unconventional, haha. Thanks for accepting the PR!
