### ISSUE TITLE
kicad2vrml core dumped on segmentation fault, compiled on Fedora36

### ISSUE THREAD

**Issue by frippe75** [diorcety/KiBlenderCad#4]
Hi,

Had trouble compiling in the first place so could be connected with that.

```
Core was generated by `./kicad2vrml'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/503467' in core file too small.
#0  0x0000000001080aae in ?? ()
(gdb) backtrace 
#0  0x0000000001080aae in  ()
#1  0x00000000010a5fde in  ()
#2  0x00000000010aad0d in  ()
#3  0x00000000006348e8 in  ()
#4  0x00007f36ca834022 in wxEntry(int&, wchar_t**) (argc=<optimized out>, argv=<optimized out>) at ../src/common/init.cpp:490
#5  0x00000000006084a8 in  ()
#6  0x00007f36c95ba550 in __libc_start_call_main (main=main@entry=0x608480, argc=argc@entry=1, argv=argv@entry=0x7ffd5d2ad2f8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#7  0x00007f36c95ba609 in __libc_start_main_impl
     (main=0x608480, argc=1, argv=0x7ffd5d2ad2f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd5d2ad2e8) at ../csu/libc-start.c:389
#8  0x0000000000631ed5 in _start ()
```

Maybe recompile with debug...

**Comment by frippe75** [comment]
```
[frta@localhost-live kicad2vrml]$ ./kicad2vrml 
/home/frta/kicad/kicad/pcbnew/pcbnew.cpp(218): assert "process" failed in Pgm().


Call stack:
[00] SystemDirsAppend(SEARCH_STACK*)         	/home/frta/kicad/kicad/common/systemdirsappend.cpp:77
[01] PGM_BASE::SetLanguagePath()             	/home/frta/kicad/kicad/common/pgm_base.cpp:787
[02] PGM_BASE::InitPgm()                     	/home/frta/kicad/kicad/common/pgm_base.cpp:317
[03] PGM_KICAD2VRML_TOP::OnPgmInit()         	/home/frta/kicad/kicad/kicad2vrml/kicad2vrml.cpp:169
[04] APP_KICAD2VRML::OnInit()                	/home/frta/kicad/kicad/kicad2vrml/kicad2vrml.cpp:257
[05] wxAppConsoleBase::CallOnInit()          	/usr/include/wx-3.0/wx/app.h:93
[06] wxEntry(int&, wchar_t**)                
[07] main                                    	/home/frta/kicad/kicad/kicad2vrml/kicad2vrml.cpp:368
[08] 0x7f60f4721550
[09] __libc_start_main                       
[10] _start                                  
Segmentation fault (core dumped)
```
